# https://rust-lang.github.io/rustfmt/?version=master
format_generated_files = true
	
hard_tabs = true
max_width = 130
imports_granularity = "Crate"
reorder_impl_items = true

use_field_init_shorthand = true
# trailing_comma = "Never"

skip_macro_invocations = ["*"]
single_line_if_else_max_width = 0
format_strings = false
# normalize_comments = true