[package]
name = "tg"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
derive_more = { version = "1", features = ["from"] }
serde = { version = "1", features = ["derive"] }
serde_with = { version = "3.12" }

# optional
serde_json = { version = "1", optional = true }

[dev-dependencies]

[features]
client = []
serializer = ["dep:serde_json"]