[package]
name = "tg"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
derive_more = { version = "1", features = ["from"] }
serde = { version = "1", features = ["derive"] }
serde_with = { version = "3.12" }

# optional
reqwest = { version = "0.12", default-features = false, optional = true }
serde_json = { version = "1", optional = true }

[dev-dependencies]

[features]
reqwest = ["dep:reqwest"]
serializer = ["dep:serde_json"]